---
services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    container_name: jellyseerr
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=${JELLYSEERR_PORT} #optional
    ports:
      - ${JELLYSEERR_PORT}:${JELLYSEERR_PORT}
    volumes:
      - ./data/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${JELLYSEERR_PORT}/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped