services:
  #---------------------------------------------------------------------#
  #     Speedtest Tracker - Self-hosted internet performance tracking.  #
  #---------------------------------------------------------------------#
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SPEEDTEST_PORT}:80
      - 8443:443
    environment:
      PUID: 1000
      PGID: 1000
      APP_KEY: ${SPEEDTEST_APP_KEY}   # Generate with: openssl rand -base64 32
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/speedtest:/config
      - ./data/keys:/config/keys
    depends_on:
      - db
    labels:
      - "diun.enable=true"
      - "diun.include_tags=latest"
      - "diun.watch_repo=true"

  #---------------------------------------------------------------------#
  #     PostgreSQL Database for Speedtest Tracker                       #
  #---------------------------------------------------------------------#
  db:
    image: postgres:17
    container_name: speedtest-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5