services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes: 
      - ./data/config:/config
      - ${RADARR_DATA_PATH}:/data
    ports:
      - ${RADARR_PORT}:7878