watch:
  firstCheckNotif: true

providers:
  docker:
    watchByDefault: false
  file:
    filename: /config/images.yaml

notif:
  gotify:
    templateTitle: "{{ .Entry.Image }} released"

db:
  path: /data/diun.db