services:
  #---------------------------------------------------------------------#
  #     Nginx Proxy Manager - Proxy Manager.                            #
  #---------------------------------------------------------------------#
  nginxproxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - ${NGINX_PUBLIC_PORT}:80        # Public HTTP Port
      - ${NGINX_PUBLIC_HTTPS_PORT}:443 # Public HTTPS Port
      - ${NGINX_WEB_PORT}:81           # Nginx Proxy Manager Web UI
    env_file:
      - .env
    environment:
      # PostgreSQL parameters
      DB_POSTGRES_HOST: postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
    depends_on:
      - postgres
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-manager
      - default
    labels:
      - "diun.enable=true"
      - "diun.include_tags=latest"
      - "diun.watch_repo=true"

  #---------------------------------------------------------------------#
  #     PostgreSQL Database for Nginx Proxy Manager                     #
  #---------------------------------------------------------------------#
  postgres:
    image: postgres:17
    container_name: nginx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_POSTGRES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nginx-proxy-manager

#---------------------------------------------------------------------#
#     Networks                                                        #
#---------------------------------------------------------------------#
networks:
  nginx-proxy-manager:
    driver: bridge