services:
#---------------------------------------------------------------------#
#     Portainer Agent - For Portainer Access.                         #
#---------------------------------------------------------------------#
  agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    env_file: 
      - .env
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./data/portainer-agent:/data
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    labels:
      - "diun.enable=true"
      - "diun.watch_repos=true"
#---------------------------------------------------------------------#
#     Portainer - Web UI Management of Docker Containers.             #
#---------------------------------------------------------------------#
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    env_file: 
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./data/portainer:/data
    ports:
      - ${PORTAINER_WEB_PORT}:9000
      - ${PORTAINER_PORT}:8000
    labels:
      - "diun.enable=true"
      - "diun.watch_repos=true"