services:
#---------------------------------------------------------------------#
#     Homepage - A modern,fully static application dashboard.         #
#---------------------------------------------------------------------#
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    ports:
      - ${HOMEPAGE_PORT}:3000 # host:docker
    env_file:
      - .env
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_HOST}:${HOMEPAGE_PORT}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/config
      - ./images:/app/public/images