services:
#---------------------------------------------------------------------#
#     qBittorrent - Torrent Management.                               #
#---------------------------------------------------------------------#
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - TORRENTING_PORT=${QBITTORRENT_PORT}
    volumes:
      - ./data/config:/config
      - ${QBITTORRENT_TORRENTS_PATH}:/data/torrents # Path to store torrent data
      - ${QBITTORRENT_MEDIA_PATH}:/media # Path to main media directory for proper file handling
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT} # qBittorrent Web UI
      - ${QBITTORRENT_LISTENING_PORT}:${QBITTORRENT_LISTENING_PORT} # qBittorrent Listening port
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT} # qbittorrent
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}/udp # qbittorrent

