services:
#---------------------------------------------------------------------#
#     Audiobookshelf - Audiobook Manager.                             #
#---------------------------------------------------------------------#
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ${AUDIOBOOKSHELF_AUDIOBOOK_PATH}:/audiobooks # Path To Audiobooks
      - ${AUDIOBOOKSHELF_PODCAST_PATH}:/podcasts # Path To Podcasts
      - ./data/metadata:/metadata
      - ./data/config:/config


