services:
#---------------------------------------------------------------------#
#     Audiobookshelf - Audiobook Manager.                             #
#---------------------------------------------------------------------#
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: always
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ${AUDIOBOOKSHELF_AUDIOBOOK_PATH}:/audiobooks
      - ${AUDIOBOOKSHELF_PODCAST_PATH}:/podcasts
      - audiobookshelf_metadata:/metadata
      - audiobookshelf_config:/config

volumes:
  audiobookshelf_metadata:
    driver: local
  audiobookshelf_config:
    driver: local
